In [1]:
import numpy as np

X = 2 * np.random.rand(100, 1)
y = 4 + 3 * X + np.random.randn(100, 1)

In [2]:
X

array([[1.13983454],
       [0.38081047],
       [1.55019891],
       [0.25399191],
       [0.06840317],
       [0.12117041],
       [0.66610435],
       [1.78591899],
       [1.46767062],
       [1.39290659],
       [0.7695602 ],
       [0.48395006],
       [0.65691524],
       [0.04740809],
       [0.01381067],
       [0.30737663],
       [0.06537643],
       [1.0106356 ],
       [0.19477843],
       [1.12873781],
       [0.48037966],
       [1.70849074],
       [0.16572928],
       [1.43104347],
       [1.16397841],
       [1.32103666],
       [0.91162376],
       [1.08222716],
       [0.24426609],
       [1.63060726],
       [0.40436909],
       [1.56946187],
       [0.74358927],
       [0.74430968],
       [0.59753983],
       [1.41899608],
       [1.35553971],
       [0.32494635],
       [0.40358355],
       [1.66071954],
       [1.21097743],
       [1.950285  ],
       [0.40885017],
       [1.69976629],
       [0.52893889],
       [0.1125122 ],
       [0.29918186],
       [0.118

In [3]:
y

array([[ 7.58293657],
       [ 5.50203918],
       [ 9.43457068],
       [ 4.38533544],
       [ 5.98380555],
       [ 2.19999728],
       [ 6.86588775],
       [ 8.78863245],
       [ 7.86329592],
       [10.35320301],
       [ 6.08298528],
       [ 6.29425636],
       [ 7.27274931],
       [ 4.53097868],
       [ 3.91254437],
       [ 6.01939576],
       [ 3.95050372],
       [ 6.31539964],
       [ 4.58401251],
       [ 7.20946201],
       [ 4.52065355],
       [ 9.35262832],
       [ 5.24323022],
       [ 9.42921564],
       [ 7.16014446],
       [ 7.50503298],
       [ 7.21701603],
       [ 5.76536577],
       [ 5.45389505],
       [ 7.89027221],
       [ 4.88238351],
       [ 6.95130402],
       [ 6.41562542],
       [ 5.49589918],
       [ 4.19450629],
       [ 6.52171883],
       [ 9.92428199],
       [ 4.34091252],
       [ 2.76913466],
       [ 8.94853598],
       [ 6.39484577],
       [ 9.34816836],
       [ 5.19383329],
       [ 9.87046937],
       [ 6.1694344 ],
       [ 4

In [8]:
from keras.layers import dot

ModuleNotFoundError: No module named 'keras'

In [9]:
X_b = np.c_[np.ones((100, 1)), X]
theta_best = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)

In [10]:
theta_best

array([[3.99064908],
       [2.90185202]])